#!/bin/sh

set -e

. /usr/share/cups/ppd-updaters/printer-driver-hpijs.ppd-updater

# As of hplip 3.19.8, there are 800 printers supported by hpijs; so don't test them _all_.
# Get the list of drivers from lpinfo here;
# Skip the faxes
# Only take every 25th driver
HPIJS_DRIVERS_LIST=$(lpinfo -m | cut -f1 -d' ' | grep -v 'HP-Fax' | grep -E $DRIVER_REGEXP | sed -n '0~25p')

/usr/share/cups/test-drivers -n adt-test-hpijs-0 -l "$HPIJS_DRIVERS_LIST"
