#!/bin/sh

set -e

. /usr/share/cups/ppd-updaters/printer-driver-hpcups.ppd-updater

# As of hplip 3.19.8, there are 806 printers supported by hpcups; so don't test them _all_.
# Get the list of drivers from lpinfo here, but only take every 25th driver
HPCUPS_DRIVERS_LIST=$(lpinfo -m | cut -f1 -d' ' | grep -E $DRIVER_REGEXP | sed -n '0~25p')

/usr/share/cups/test-drivers -n adt-test-hpcups-0 -l "$HPCUPS_DRIVERS_LIST"
