#!/bin/sh

set -e

# Build a list of driver names from the .drv file, excluding these that say they need a proprietary driver
# Take all drivers
HPCUPS_DRIVERS_LIST=$(
    grep -A4 -P 'NickName.*Version(?!, requires proprietary plugin)\"$' /usr/share/cups/drv/hpcups.drv | \
    grep -E '^ *PCFileName' | \
    sed -e 's#^ *PCFileName "\(.*\)"$#drv:///hpcups.drv/\1#g'
)

# … but print only one PDF
PDFS_PATH=`mktemp -d`
cp /usr/share/cups/data/default-testpage.pdf $PDFS_PATH/

/usr/share/cups/test-drivers -n adt-test-hpcups-0 -p $PDFS_PATH -l "$HPCUPS_DRIVERS_LIST"
